# Generated by Django 5.1.3 on 2024-12-20 09:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0002_organizations_typesofproducts_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('number', models.CharField(max_length=128, verbose_name='Номер')),
                ('agreement', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agreement_order', to='catalogs.agreement', verbose_name='Соглашения')),
                ('contract', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract_order', to='catalogs.contract', verbose_name='Договор')),
                ('counterparty', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='counterparty_order', to='catalogs.counterparty', verbose_name='Контрагент')),
                ('organization', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='organization_order', to='catalogs.organizations', verbose_name='Организация')),
                ('partner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='partner_order', to=settings.AUTH_USER_MODEL, verbose_name='Партнер')),
            ],
            options={
                'verbose_name': 'Заказ клиента',
                'verbose_name_plural': 'Заказы клиента',
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена')),
                ('quntity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма')),
                ('characteristic', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, related_name='characteristics_orders_detail', to='catalogs.characteristics', verbose_name='Характеристика')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='product_orders_detail', to='catalogs.products', verbose_name='Номенклатура')),
                ('order', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='order_orders_detail', to='documents.orders', verbose_name='Заказ клиента')),
            ],
            options={
                'verbose_name': 'Заказ клиента (товары)',
                'verbose_name_plural': 'Заказы клиента (товары)',
            },
        ),
    ]
