# Generated by Django 5.1.3 on 2025-01-13 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0003_alter_products_use_characteristics'),
        ('documents', '0002_exchangenode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='side_status',
            field=models.CharField(choices=[('CR', 'Создан'), ('WR', 'Записан'), ('PR', 'Обработан'), ('CL', 'Закрыт')], default='CR', max_length=10, verbose_name='Статус заказа на сайте'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='counterparty',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='counterparty_order', to='catalogs.counterparty', verbose_name='Контрагент'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='number',
            field=models.CharField(default='', max_length=128, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='organization',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organization_order', to='catalogs.organizations', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='partner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partner_order', to=settings.AUTH_USER_MODEL, verbose_name='Партнер'),
        ),
    ]
