# Generated by Django 5.1.3 on 2024-12-18 08:31

import catalogs.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.CreateModel(
            name='TypesOfProducts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Вид номенклатуры',
                'verbose_name_plural': 'Виды номенклатуры',
            },
        ),
        migrations.AddField(
            model_name='products',
            name='use_characteristics',
            field=models.CharField(choices=[('NU', 'Не используются'), ('GEN', 'Общие для вида номенклатуры'), ('IND', 'Индивидуальные для номенклатуры')], default='NU', max_length=20, verbose_name='Варианты использования характеристик номенклатуры'),
        ),
        migrations.CreateModel(
            name='CounterParty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Наименование')),
                ('full_name', models.CharField(blank=True, max_length=250, unique=True, verbose_name='Сокращенное юр. наименование')),
                ('status', models.CharField(choices=[('COMP', 'Компания'), ('PRIV', 'Частное лицо')], default='COMP', max_length=20, verbose_name='Юр/Физ. лицо')),
                ('inn', models.CharField(max_length=12, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=9, null=True, verbose_name='КПП')),
                ('partner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='counterparty', to=settings.AUTH_USER_MODEL, verbose_name='Партнер')),
            ],
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('number', models.CharField(max_length=30, verbose_name='Номер')),
                ('date', models.DateField(verbose_name='Дата')),
                ('partner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partner_agreement', to=settings.AUTH_USER_MODEL, verbose_name='Партнер')),
                ('counterparty', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='counterparty_agreement', to='catalogs.counterparty', verbose_name='Контрагент')),
            ],
            options={
                'verbose_name': 'Соглашение об условиях продаж',
                'verbose_name_plural': 'Соглашения об условиях продаж',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(default=None, upload_to=catalogs.models.image_directory_path, verbose_name='Картинка')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_images', to='catalogs.products', verbose_name='Наименование картинок')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинки',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('number', models.CharField(max_length=120, verbose_name='Номер')),
                ('date', models.DateField(verbose_name='Дата')),
                ('partner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='partner_contract', to=settings.AUTH_USER_MODEL, verbose_name='Партнер')),
                ('counterparty', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='counterparty_contract', to='catalogs.counterparty', verbose_name='Контрагент')),
                ('organization', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='organization_contract', to='catalogs.organizations', verbose_name='Организация')),
            ],
        ),
        migrations.CreateModel(
            name='Characteristics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Наимнование')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_characteristics', to='catalogs.products', verbose_name='Номенклатура')),
                ('type_of_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='type_of_product_characteristics', to='catalogs.typesofproducts', verbose_name='Вид номенклатуры')),
            ],
            options={
                'verbose_name': 'Характеристика номенклатуры',
                'verbose_name_plural': 'Характеристики номенклатуры',
            },
        ),
        migrations.AddField(
            model_name='products',
            name='type_of_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='type_of_product_products', to='catalogs.typesofproducts', verbose_name='Вид номеклатуры'),
        ),
    ]
