# Generated by Django 5.1.3 on 2025-01-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0002_organizations_typesofproducts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='use_characteristics',
            field=models.CharField(choices=[('NU', 'Не используются'), ('GEN', 'Общие для вида номенклатуры'), ('OTH', 'Общие с другим видом номенклатуры'), ('IND', 'Индивидуальные для номенклатуры')], default='NU', max_length=20, verbose_name='Варианты использования характеристик номенклатуры'),
        ),
    ]
